//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAll4Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAll4Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _360_fades {
            get {
                object obj = ResourceManager.GetObject("_360_fades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _checked {
            get {
                object obj = ResourceManager.GetObject("_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap A {
            get {
                object obj = ResourceManager.GetObject("A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Name of this action already exists 的本地化字符串。
        /// </summary>
        internal static string ActionExists {
            get {
                return ResourceManager.GetString("ActionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding to list... 的本地化字符串。
        /// </summary>
        internal static string AddingToList {
            get {
                return ResourceManager.GetString("AddingToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Programs 的本地化字符串。
        /// </summary>
        internal static string AddPrograms {
            get {
                return ResourceManager.GetString("AddPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A location must be picked to continue. 的本地化字符串。
        /// </summary>
        internal static string ALocactionNeeded {
            get {
                return ResourceManager.GetString("ALocactionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Rainbow Mode 的本地化字符串。
        /// </summary>
        internal static string AlwaysRainbow {
            get {
                return ResourceManager.GetString("AlwaysRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign to Controller *number* 的本地化字符串。
        /// </summary>
        internal static string AssignProfile {
            get {
                return ResourceManager.GetString("AssignProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap B {
            get {
                object obj = ResourceManager.GetObject("B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BACK {
            get {
                object obj = ResourceManager.GetObject("BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Battery: *number*% 的本地化字符串。
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Best used with right side as a mouse function 的本地化字符串。
        /// </summary>
        internal static string BestUsedRightSide {
            get {
                return ResourceManager.GetString("BestUsedRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BT {
            get {
                object obj = ResourceManager.GetObject("BT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot move files to new location, Please rename the EAll4Tool folder to &quot;EAll4Windows&quot; 的本地化字符串。
        /// </summary>
        internal static string CannotMoveFiles {
            get {
                return ResourceManager.GetString("CannotMoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write at current locataion. Copy Settings to appdata? 的本地化字符串。
        /// </summary>
        internal static string CannotWriteHere {
            get {
                return ResourceManager.GetString("CannotWriteHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charged 的本地化字符串。
        /// </summary>
        internal static string Charged {
            get {
                return ResourceManager.GetString("Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charging: *number*% 的本地化字符串。
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Battery 的本地化字符串。
        /// </summary>
        internal static string CheckBattery {
            get {
                return ResourceManager.GetString("CheckBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close EAll4Windows? 的本地化字符串。
        /// </summary>
        internal static string CloseEAll4W {
            get {
                return ResourceManager.GetString("CloseEAll4W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close EAll4Windows via the notification icon 的本地化字符串。
        /// </summary>
        internal static string CloseMinimize {
            get {
                return ResourceManager.GetString("CloseMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color by Battery % 的本地化字符串。
        /// </summary>
        internal static string ColorByBattery {
            get {
                return ResourceManager.GetString("ColorByBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting... 的本地化字符串。
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Profile for Controller *number* 的本地化字符串。
        /// </summary>
        internal static string ContextEdit {
            get {
                return ResourceManager.GetString("ContextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Profile for Controller *number* 的本地化字符串。
        /// </summary>
        internal static string ContextNew {
            get {
                return ResourceManager.GetString("ContextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller *Mac address* was removed or lost connection 的本地化字符串。
        /// </summary>
        internal static string ControllerWasRemoved {
            get {
                return ResourceManager.GetString("ControllerWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Copy complete, please relaunch EAll4Windows and remove settings from Program Directory 的本地化字符串。
        /// </summary>
        internal static string CopyComplete {
            get {
                return ResourceManager.GetString("CopyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to copy the full color 的本地化字符串。
        /// </summary>
        internal static string CopyFullColor {
            get {
                return ResourceManager.GetString("CopyFullColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Could not open EAll4 *Mac address* exclusively. 的本地化字符串。
        /// </summary>
        internal static string CouldNotOpenEAll4 {
            get {
                return ResourceManager.GetString("CouldNotOpenEAll4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 days 的本地化字符串。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Profile? 的本地化字符串。
        /// </summary>
        internal static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dim by Battey % 的本地化字符串。
        /// </summary>
        internal static string DimByBattery {
            get {
                return ResourceManager.GetString("DimByBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off X360 input and only use the EAll4&apos;s native input, hide eall4 must be off (Wired Only) 的本地化字符串。
        /// </summary>
        internal static string DinputOnly {
            get {
                return ResourceManager.GetString("DinputOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect BT 的本地化字符串。
        /// </summary>
        internal static string DisconnectBT {
            get {
                return ResourceManager.GetString("DisconnectBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DOWN {
            get {
                object obj = ResourceManager.GetObject("DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading *number*% 的本地化字符串。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Version *number* now? 的本地化字符串。
        /// </summary>
        internal static string DownloadVersion {
            get {
                return ResourceManager.GetString("DownloadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string DownText {
            get {
                return ResourceManager.GetString("DownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon EAll4 {
            get {
                object obj = ResourceManager.GetObject("EAll4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EAll4_Controller {
            get {
                object obj = ResourceManager.GetObject("EAll4_Controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 EAll4Windows Update Available! 的本地化字符串。
        /// </summary>
        internal static string EAll4Update {
            get {
                return ResourceManager.GetString("EAll4Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon EAll4W {
            get {
                object obj = ResourceManager.GetObject("EAll4W", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 EAll4Windows cannot edit settings here, This will now close 的本地化字符串。
        /// </summary>
        internal static string EAll4WindowsCannotEditHere {
            get {
                return ResourceManager.GetString("EAll4WindowsCannotEditHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream EE {
            get {
                return ResourceManager.GetStream("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Fall Back 的本地化字符串。
        /// </summary>
        internal static string FallBack {
            get {
                return ResourceManager.GetString("FallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fall Back to *button* 的本地化字符串。
        /// </summary>
        internal static string FallBackTo {
            get {
                return ResourceManager.GetString("FallBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5th Mouse Button Down 的本地化字符串。
        /// </summary>
        internal static string FifthMouseDown {
            get {
                return ResourceManager.GetString("FifthMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5th Mouse Button Up 的本地化字符串。
        /// </summary>
        internal static string FifthMouseUp {
            get {
                return ResourceManager.GetString("FifthMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to change flash color. Black = default color 的本地化字符串。
        /// </summary>
        internal static string FlashAtTip {
            get {
                return ResourceManager.GetString("FlashAtTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flush HID 的本地化字符串。
        /// </summary>
        internal static string FlushHID {
            get {
                return ResourceManager.GetString("FlushHID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flush HID Queue after each reading 的本地化字符串。
        /// </summary>
        internal static string FlushHIDTip {
            get {
                return ResourceManager.GetString("FlushHIDTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found Controller: 的本地化字符串。
        /// </summary>
        internal static string FoundController {
            get {
                return ResourceManager.GetString("FoundController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4th Mouse Button Down 的本地化字符串。
        /// </summary>
        internal static string FourthMouseDown {
            get {
                return ResourceManager.GetString("FourthMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4th Mouse Button Up 的本地化字符串。
        /// </summary>
        internal static string FourthMouseUp {
            get {
                return ResourceManager.GetString("FourthMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full 的本地化字符串。
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to see readout of Sixaxis Gyro 的本地化字符串。
        /// </summary>
        internal static string GyroReadout {
            get {
                return ResourceManager.GetString("GyroReadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GyroX, Left and Right Tilt 的本地化字符串。
        /// </summary>
        internal static string GyroX {
            get {
                return ResourceManager.GetString("GyroX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GyroY, Forward and Back Tilt 的本地化字符串。
        /// </summary>
        internal static string GyroY {
            get {
                return ResourceManager.GetString("GyroY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GyroZ, Up and Down Tilt 的本地化字符串。
        /// </summary>
        internal static string GyroZ {
            get {
                return ResourceManager.GetString("GyroZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour 的本地化字符串。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hours 的本地化字符串。
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hover over items to see description or more about 的本地化字符串。
        /// </summary>
        internal static string HoverOverItems {
            get {
                return ResourceManager.GetString("HoverOverItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If removing EAll4Windows, You can delete the settings following the profile folder link 的本地化字符串。
        /// </summary>
        internal static string IfRemovingEAll4Windows {
            get {
                return ResourceManager.GetString("IfRemovingEAll4Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Input Delay: *number*ms 的本地化字符串。
        /// </summary>
        internal static string InputDelay {
            get {
                return ResourceManager.GetString("InputDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Complete 的本地化字符串。
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Drivers here 的本地化字符串。
        /// </summary>
        internal static string InstallDriver {
            get {
                return ResourceManager.GetString("InstallDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Failed, Please Retry 的本地化字符串。
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing... 的本地化字符串。
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Sixaxis to help calculate touchpad movement 的本地化字符串。
        /// </summary>
        internal static string Jitter {
            get {
                return ResourceManager.GetString("Jitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep this window size after closing 的本地化字符串。
        /// </summary>
        internal static string KeepThisSize {
            get {
                return ResourceManager.GetString("KeepThisSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller *number*&apos;s latency now under 10ms 的本地化字符串。
        /// </summary>
        internal static string LatencyNotOverTen {
            get {
                return ResourceManager.GetString("LatencyNotOverTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller *number*&apos;s latency over 10ms 的本地化字符串。
        /// </summary>
        internal static string LatencyOverTen {
            get {
                return ResourceManager.GetString("LatencyOverTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch *program* 的本地化字符串。
        /// </summary>
        internal static string LaunchProgram {
            get {
                return ResourceManager.GetString("LaunchProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LB {
            get {
                object obj = ResourceManager.GetObject("LB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LEFT {
            get {
                object obj = ResourceManager.GetObject("LEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LeftTouch {
            get {
                object obj = ResourceManager.GetObject("LeftTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Also dim light by idle timeout if on 的本地化字符串。
        /// </summary>
        internal static string LightByBatteryTip {
            get {
                return ResourceManager.GetString("LightByBatteryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load *profile* 的本地化字符串。
        /// </summary>
        internal static string LoadProfile {
            get {
                return ResourceManager.GetString("LoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LS {
            get {
                object obj = ResourceManager.GetObject("LS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LSD {
            get {
                object obj = ResourceManager.GetObject("LSD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LSL {
            get {
                object obj = ResourceManager.GetObject("LSL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LSR {
            get {
                object obj = ResourceManager.GetObject("LSR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LSU {
            get {
                object obj = ResourceManager.GetObject("LSU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LT {
            get {
                object obj = ResourceManager.GetObject("LT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Macro 的本地化字符串。
        /// </summary>
        internal static string Macro {
            get {
                return ResourceManager.GetString("Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make a New Profile 的本地化字符串。
        /// </summary>
        internal static string MakeNewProfile {
            get {
                return ResourceManager.GetString("MakeNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap mouse {
            get {
                object obj = ResourceManager.GetObject("mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MultiTouch {
            get {
                object obj = ResourceManager.GetObject("MultiTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap newprofile {
            get {
                object obj = ResourceManager.GetObject("newprofile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 No macro was recorded 的本地化字符串。
        /// </summary>
        internal static string NoMacroRecorded {
            get {
                return ResourceManager.GetString("NoMacroRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap none {
            get {
                object obj = ResourceManager.GetObject("none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 (none) 的本地化字符串。
        /// </summary>
        internal static string noneProfile {
            get {
                return ResourceManager.GetString("noneProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 none 的本地化字符串。
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Profile Loaded 的本地化字符串。
        /// </summary>
        internal static string NoProfileLoaded {
            get {
                return ResourceManager.GetString("NoProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller *number* is not using a profile 的本地化字符串。
        /// </summary>
        internal static string NotUsingProfile {
            get {
                return ResourceManager.GetString("NotUsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not valid 的本地化字符串。
        /// </summary>
        internal static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening Installer 的本地化字符串。
        /// </summary>
        internal static string OpeningInstaller {
            get {
                return ResourceManager.GetString("OpeningInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Open ScpDriver.exe 的本地化字符串。
        /// </summary>
        internal static string OpenScpDriver {
            get {
                return ResourceManager.GetString("OpenScpDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , other location files will be deleted 的本地化字符串。
        /// </summary>
        internal static string OtherFileLocation {
            get {
                return ResourceManager.GetString("OtherFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Pairmode {
            get {
                object obj = ResourceManager.GetObject("Pairmode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Please Download the Updater now, and place it in the programs folder, then check for update again 的本地化字符串。
        /// </summary>
        internal static string PleaseDownloadUpdater {
            get {
                return ResourceManager.GetString("PleaseDownloadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please import or make a profile 的本地化字符串。
        /// </summary>
        internal static string PleaseImport {
            get {
                return ResourceManager.GetString("PleaseImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Profile 的本地化字符串。
        /// </summary>
        internal static string PlusNewProfile {
            get {
                return ResourceManager.GetString("PlusNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *Profile name* cannot be restored. 的本地化字符串。
        /// </summary>
        internal static string ProfileCannotRestore {
            get {
                return ResourceManager.GetString("ProfileCannotRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile Folder Moved to program folder 的本地化字符串。
        /// </summary>
        internal static string ProfileFolderMoved {
            get {
                return ResourceManager.GetString("ProfileFolderMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Programs 的本地化字符串。
        /// </summary>
        internal static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EXPERIMENTAL: Auto-Disable BT when conencting to USB 的本地化字符串。
        /// </summary>
        internal static string QuickCharge {
            get {
                return ResourceManager.GetString("QuickCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must quit other applications like Steam, Uplay before activating the &apos;Hide EAll4 Controller&apos; option.&quot; 的本地化字符串。
        /// </summary>
        internal static string QuitOtherPrograms {
            get {
                return ResourceManager.GetString("QuitOtherPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rainbow {
            get {
                object obj = ResourceManager.GetObject("rainbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rainbowC {
            get {
                object obj = ResourceManager.GetObject("rainbowC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RB {
            get {
                object obj = ResourceManager.GetObject("RB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        internal static string RecordText {
            get {
                return ResourceManager.GetString("RecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RIGHT {
            get {
                object obj = ResourceManager.GetObject("RIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Right Click to set presets for a set of controls 的本地化字符串。
        /// </summary>
        internal static string RightClickPresets {
            get {
                return ResourceManager.GetString("RightClickPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RightTouch {
            get {
                object obj = ResourceManager.GetObject("RightTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RS {
            get {
                object obj = ResourceManager.GetObject("RS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RSD {
            get {
                object obj = ResourceManager.GetObject("RSD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RSL {
            get {
                object obj = ResourceManager.GetObject("RSL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RSR {
            get {
                object obj = ResourceManager.GetObject("RSR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RSU {
            get {
                object obj = ResourceManager.GetObject("RSU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RT {
            get {
                object obj = ResourceManager.GetObject("RT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap saveprofile {
            get {
                object obj = ResourceManager.GetObject("saveprofile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Save Recorded Macro? 的本地化字符串。
        /// </summary>
        internal static string SaveRecordedMacro {
            get {
                return ResourceManager.GetString("SaveRecordedMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Code 的本地化字符串。
        /// </summary>
        internal static string ScanCode {
            get {
                return ResourceManager.GetString("ScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching for controllers… 的本地化字符串。
        /// </summary>
        internal static string SearchingController {
            get {
                return ResourceManager.GetString("SearchingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an action for *action* 的本地化字符串。
        /// </summary>
        internal static string SelectActionTitle {
            get {
                return ResourceManager.GetString("SelectActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Regular Trigger 的本地化字符串。
        /// </summary>
        internal static string SetRegularTrigger {
            get {
                return ResourceManager.GetString("SetRegularTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Unload Trigger 的本地化字符串。
        /// </summary>
        internal static string SetUnloadTrigger {
            get {
                return ResourceManager.GetString("SetUnloadTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcuts 的本地化字符串。
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click for advanced Sixaxis reading 的本地化字符串。
        /// </summary>
        internal static string SixAxisReading {
            get {
                return ResourceManager.GetString("SixAxisReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap size {
            get {
                object obj = ResourceManager.GetObject("size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap START {
            get {
                object obj = ResourceManager.GetObject("START", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Starting... 的本地化字符串。
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 1: Install the EAll4 Driver 的本地化字符串。
        /// </summary>
        internal static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sticks {
            get {
                object obj = ResourceManager.GetObject("sticks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Heavy 的本地化字符串。
        /// </summary>
        internal static string StopHText {
            get {
                return ResourceManager.GetString("StopHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Light 的本地化字符串。
        /// </summary>
        internal static string StopLText {
            get {
                return ResourceManager.GetString("StopLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped EAll4 Tool 的本地化字符串。
        /// </summary>
        internal static string StoppedEAll4Tool {
            get {
                return ResourceManager.GetString("StoppedEAll4Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped EAll4Windows 的本地化字符串。
        /// </summary>
        internal static string StoppedEAll4Windows {
            get {
                return ResourceManager.GetString("StoppedEAll4Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping EAll4 Controllers 的本地化字符串。
        /// </summary>
        internal static string StoppingEAll4 {
            get {
                return ResourceManager.GetString("StoppingEAll4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping X360 Controllers 的本地化字符串。
        /// </summary>
        internal static string StoppingX360 {
            get {
                return ResourceManager.GetString("StoppingX360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swipe Down 的本地化字符串。
        /// </summary>
        internal static string SwipeDown {
            get {
                return ResourceManager.GetString("SwipeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swipe Left 的本地化字符串。
        /// </summary>
        internal static string SwipeLeft {
            get {
                return ResourceManager.GetString("SwipeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swipe Right 的本地化字符串。
        /// </summary>
        internal static string SwipeRight {
            get {
                return ResourceManager.GetString("SwipeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swipe Touchpad to change profiles 的本地化字符串。
        /// </summary>
        internal static string SwipeTouchpad {
            get {
                return ResourceManager.GetString("SwipeTouchpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swipe Up 的本地化字符串。
        /// </summary>
        internal static string SwipeUp {
            get {
                return ResourceManager.GetString("SwipeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap and hold to drag, slight delay with single taps 的本地化字符串。
        /// </summary>
        internal static string TapAndHold {
            get {
                return ResourceManager.GetString("TapAndHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Heavy 的本地化字符串。
        /// </summary>
        internal static string TestHText {
            get {
                return ResourceManager.GetString("TestHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Light 的本地化字符串。
        /// </summary>
        internal static string TestLText {
            get {
                return ResourceManager.GetString("TestLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tilt Down 的本地化字符串。
        /// </summary>
        internal static string TiltDown {
            get {
                return ResourceManager.GetString("TiltDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tilt Left 的本地化字符串。
        /// </summary>
        internal static string TiltLeft {
            get {
                return ResourceManager.GetString("TiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tilt Right 的本地化字符串。
        /// </summary>
        internal static string TiltRight {
            get {
                return ResourceManager.GetString("TiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tilt Up 的本地化字符串。
        /// </summary>
        internal static string TiltUp {
            get {
                return ResourceManager.GetString("TiltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touchpad Movement is now Off 的本地化字符串。
        /// </summary>
        internal static string TouchpadMovementOff {
            get {
                return ResourceManager.GetString("TouchpadMovementOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touchpad Movement is now On 的本地化字符串。
        /// </summary>
        internal static string TouchpadMovementOn {
            get {
                return ResourceManager.GetString("TouchpadMovementOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-enable by pressing Guide+Touchpad 的本地化字符串。
        /// </summary>
        internal static string TouchpadOffTip {
            get {
                return ResourceManager.GetString("TouchpadOffTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 finger touchpad swipe left or right 的本地化字符串。
        /// </summary>
        internal static string TwoFingerSwipe {
            get {
                return ResourceManager.GetString("TwoFingerSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type new name here 的本地化字符串。
        /// </summary>
        internal static string TypeNewName {
            get {
                return ResourceManager.GetString("TypeNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type profile name here 的本地化字符串。
        /// </summary>
        internal static string TypeProfileName {
            get {
                return ResourceManager.GetString("TypeProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UP {
            get {
                object obj = ResourceManager.GetObject("UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UpperTouch {
            get {
                object obj = ResourceManager.GetObject("UpperTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string UpText {
            get {
                return ResourceManager.GetString("UpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are up to date 的本地化字符串。
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap USB {
            get {
                object obj = ResourceManager.GetObject("USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 You can also use your controller to change controls 的本地化字符串。
        /// </summary>
        internal static string UseControllerForMapping {
            get {
                return ResourceManager.GetString("UseControllerForMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using Exclusive Mode 的本地化字符串。
        /// </summary>
        internal static string UsingExclusive {
            get {
                return ResourceManager.GetString("UsingExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller *number* is using Profile “*Profile name*&quot; 的本地化字符串。
        /// </summary>
        internal static string UsingProfile {
            get {
                return ResourceManager.GetString("UsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using Shared Mode 的本地化字符串。
        /// </summary>
        internal static string UsingShared {
            get {
                return ResourceManager.GetString("UsingShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This disables the Touchpad as a mouse 的本地化字符串。
        /// </summary>
        internal static string UsingTPSwipes {
            get {
                return ResourceManager.GetString("UsingTPSwipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid name 的本地化字符串。
        /// </summary>
        internal static string ValidName {
            get {
                return ResourceManager.GetString("ValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait *number**ms* 的本地化字符串。
        /// </summary>
        internal static string WaitMS {
            get {
                return ResourceManager.GetString("WaitMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will Keep 的本地化字符串。
        /// </summary>
        internal static string WillKeep {
            get {
                return ResourceManager.GetString("WillKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap X {
            get {
                object obj = ResourceManager.GetObject("X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Use higher ports if you get conflicts in other emulating X360 programs, such as SCP&apos;s tool 的本地化字符串。
        /// </summary>
        internal static string XinputPorts {
            get {
                return ResourceManager.GetString("XinputPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Y {
            get {
                object obj = ResourceManager.GetObject("Y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
